export const HelpMessager = {
  weakPassword: `Your password must be at least 6 characters long`,
  invalidCpfOrCnpj: 'CPF ou CNPJ invalido',
  CpfOrCnpjExitis: 'Usuário com este CPF/CNPJ já cadastrado',
  userNotFoundToken: 'User with this token not found',
  userNotFound: 'User not found',
  errorResetPasswrod: 'Error resetting password',
  passoword_or_email_invalid: 'Password or email invalid',
  accout_not_activated: 'account not activated',
  photo_not_found: 'Photo with this id not found',
  email_exits: 'Email já cadastrado',
  category_exits: 'Name this category already exitis',
  category_doNot_user: 'This category does not belong to the User Id sent',
  category_not_exits: 'This id category does not exitis',
  product_exits: 'Name this product already exitis',
  product: 'This product does not belong to the User Id sent',
  product_not_exits: 'This id product does not exitis',
  product_doNot_user: 'This product does not belong to the User Id sent',
};
