export const HelpMessager = {
  weakPassword: `Your password must be at least 6 characters long`,
  invalidCpfOrCnpj: 'CPF ou CNPJ invalido',
  CpfOrCnpjExitis: 'Usuário com este CPF/CNPJ já cadastrado',
  userNotFoundToken: 'User with this token not found',
  userNotFound: 'User not found',
  errorResetPasswrod: 'Error resetting password',
  passoword_or_email_invalid: 'Email ou senha inválidos',
  accout_not_activated: 'account not activated',
  photo_not_found: 'Foto(s) não encontradas',
  email_exits: 'Email já cadastrado',
  category_exits: 'Já existe uma categoria com este nome.',
  category_doNot_user: 'This category does not belong to the User Id sent',
  category_not_exits: 'Categoria com o ID informado não encontrado.',
  product_exits: 'Name this product already exitis',
  product: 'This product does not belong to the User Id sent',
  product_not_exits: 'This id product does not exitis',
  product_doNot_user: 'This product does not belong to the User Id sent',
  employees_exists: 'Login já cadastrado',
  employees_not_exists: 'Funcionario com o ID passado não existe',
  employee_has_photo: 'Funcionario já possuiu uma foto',
  rawMaterialExists: 'Matéria Prima com este nome já cadastrada',
  rawMaterialNotExists: 'Matéria Prima com este ID não encontrada',
  establishmentNotExists: 'Establecimento com o ID informado não encontrado',
};
